### ISSUE TITLE
adding too many characters to board, removing wrong ones

### ISSUE THREAD

**Issue by ColeWill** [den-materials/tic-tac-toe#3]
link 1 https://www.w3schools.com/jquery/jquery_dom_add.asp
link 2 http://stackoverflow.com/questions/17474888/how-to-remove-one-of-the-image-elemnt-inside-div-using-jquery

asked Troy he mentioned only being able to click a button once

**Comment by ZebGirouard** [comment]
This is resolved.  unbind() for the win!
